/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialogAction: typeof import('reka-ui')['AlertDialogAction']
    AlertDialogCancel: typeof import('reka-ui')['AlertDialogCancel']
    AlertDialogContent: typeof import('reka-ui')['AlertDialogContent']
    AlertDialogDescription: typeof import('reka-ui')['AlertDialogDescription']
    AlertDialogOverlay: typeof import('reka-ui')['AlertDialogOverlay']
    AlertDialogPortal: typeof import('reka-ui')['AlertDialogPortal']
    AlertDialogRoot: typeof import('reka-ui')['AlertDialogRoot']
    AlertDialogTitle: typeof import('reka-ui')['AlertDialogTitle']
    AlertDialogTrigger: typeof import('reka-ui')['AlertDialogTrigger']
    DemoCounterCard: typeof import('./src/components/Demo/CounterCard.vue')['default']
    DemoMemberForm: typeof import('./src/components/Demo/MemberForm.vue')['default']
    DemoMembersPanel: typeof import('./src/components/Demo/MembersPanel.vue')['default']
    DemoMemberTable: typeof import('./src/components/Demo/MemberTable.vue')['default']
    Primitive: typeof import('reka-ui')['Primitive']
    RadioGroupIndicator: typeof import('reka-ui')['RadioGroupIndicator']
    RadioGroupItem: typeof import('reka-ui')['RadioGroupItem']
    RadioGroupRoot: typeof import('reka-ui')['RadioGroupRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipArrow: typeof import('reka-ui')['TooltipArrow']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    UiButton: typeof import('./src/components/Ui/Button/index.vue')['default']
  }
}
