/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.md')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    UiButton: typeof import('./src/components/Ui/Button/index.vue')['default']
  }
}
